/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/AppNavigation`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/TabNavigator`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Camara`; params?: Router.UnknownInputParams; } | { pathname: `/screens/CodeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Configuracion`; params?: Router.UnknownInputParams; } | { pathname: `/screens/CrearUsuarioScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/GaleriaScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/InformeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/MapaAgro`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Perfil`; params?: Router.UnknownInputParams; } | { pathname: `/screens/PerfilScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/RecuperarContrasenia`; params?: Router.UnknownInputParams; } | { pathname: `/screens/SplashScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/VerificarContraseniaScreen`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/navigation/AppNavigation`; params?: Router.UnknownOutputParams; } | { pathname: `/navigation/TabNavigator`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/Camara`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/CodeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/Configuracion`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/CrearUsuarioScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/GaleriaScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/HomeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/InformeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/LoginScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/MapaAgro`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/Perfil`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/PerfilScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/RecuperarContrasenia`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/SplashScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/VerificarContraseniaScreen`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/navigation/AppNavigation${`?${string}` | `#${string}` | ''}` | `/navigation/TabNavigator${`?${string}` | `#${string}` | ''}` | `/screens/Camara${`?${string}` | `#${string}` | ''}` | `/screens/CodeScreen${`?${string}` | `#${string}` | ''}` | `/screens/Configuracion${`?${string}` | `#${string}` | ''}` | `/screens/CrearUsuarioScreen${`?${string}` | `#${string}` | ''}` | `/screens/GaleriaScreen${`?${string}` | `#${string}` | ''}` | `/screens/HomeScreen${`?${string}` | `#${string}` | ''}` | `/screens/InformeScreen${`?${string}` | `#${string}` | ''}` | `/screens/LoginScreen${`?${string}` | `#${string}` | ''}` | `/screens/MapaAgro${`?${string}` | `#${string}` | ''}` | `/screens/Perfil${`?${string}` | `#${string}` | ''}` | `/screens/PerfilScreen${`?${string}` | `#${string}` | ''}` | `/screens/RecuperarContrasenia${`?${string}` | `#${string}` | ''}` | `/screens/SplashScreen${`?${string}` | `#${string}` | ''}` | `/screens/VerificarContraseniaScreen${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/AppNavigation`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/TabNavigator`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Camara`; params?: Router.UnknownInputParams; } | { pathname: `/screens/CodeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Configuracion`; params?: Router.UnknownInputParams; } | { pathname: `/screens/CrearUsuarioScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/GaleriaScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/InformeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/MapaAgro`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Perfil`; params?: Router.UnknownInputParams; } | { pathname: `/screens/PerfilScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/RecuperarContrasenia`; params?: Router.UnknownInputParams; } | { pathname: `/screens/SplashScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/VerificarContraseniaScreen`; params?: Router.UnknownInputParams; };
    }
  }
}
